update=27.01.2017 17:31:45
version=1
last_client=kicad
[pcbnew]
version=1
LastNetListRead=
UseCmpFile=1
PadDrill=0.600000000000
PadDrillOvalY=0.600000000000
PadSizeH=1.500000000000
PadSizeV=1.500000000000
PcbTextSizeV=1.500000000000
PcbTextSizeH=1.500000000000
PcbTextThickness=0.300000000000
ModuleTextSizeV=1.000000000000
ModuleTextSizeH=1.000000000000
ModuleTextSizeThickness=0.150000000000
SolderMaskClearance=0.000000000000
SolderMaskMinWidth=0.000000000000
DrawSegmentWidth=0.200000000000
BoardOutlineThickness=0.100000000000
ModuleOutlineThickness=0.150000000000
[cvpcb]
version=1
NetIExt=net
[general]
version=1
[schematic_editor]
version=1
PageLayoutDescrFile=
PlotDirectoryName=
SubpartIdSeparator=0
SubpartFirstId=65
NetFmtName=
SpiceForceRefPrefix=0
SpiceUseNetNumbers=0
LabSize=60
[eeschema]
version=1
LibDir=lib
[eeschema/libraries]
LibName1=power
LibName2=device
LibName3=transistors
LibName4=conn
LibName5=linear
LibName6=regul
LibName7=74xx
LibName8=cmos4000
LibName9=adc-dac
LibName10=memory
LibName11=xilinx
LibName12=microcontrollers
LibName13=dsp
LibName14=microchip
LibName15=analog_switches
LibName16=motorola
LibName17=texas
LibName18=intel
LibName19=audio
LibName20=interface
LibName21=digital-audio
LibName22=philips
LibName23=display
LibName24=cypress
LibName25=siliconi
LibName26=opto
LibName27=atmel
LibName28=contrib
LibName29=valves
LibName30=utstumo
LibName31=IFS-Special
LibName32=D:/JottaCloud/Jottacloud/Prosjekt/KiCad bibliotek/libraries/ok-74logic
LibName33=D:/JottaCloud/Jottacloud/Prosjekt/KiCad bibliotek/libraries/ok-con-generic
LibName34=D:/JottaCloud/Jottacloud/Prosjekt/KiCad bibliotek/libraries/ok-diodes
LibName35=D:/JottaCloud/Jottacloud/Prosjekt/KiCad bibliotek/libraries/ok-generic
LibName36=D:/JottaCloud/Jottacloud/Prosjekt/KiCad bibliotek/libraries/ok-ic-analog
LibName37=D:/JottaCloud/Jottacloud/Prosjekt/KiCad bibliotek/libraries/ok-ic-atmel
LibName38=D:/JottaCloud/Jottacloud/Prosjekt/KiCad bibliotek/libraries/ok-ic-com
LibName39=D:/JottaCloud/Jottacloud/Prosjekt/KiCad bibliotek/libraries/ok-ic-memory
LibName40=D:/JottaCloud/Jottacloud/Prosjekt/KiCad bibliotek/libraries/ok-ic-power
LibName41=D:/JottaCloud/Jottacloud/Prosjekt/KiCad bibliotek/libraries/ok-ic-special
LibName42=D:/JottaCloud/Jottacloud/Prosjekt/KiCad bibliotek/libraries/ok-ic-stm32
LibName43=D:/JottaCloud/Jottacloud/Prosjekt/KiCad bibliotek/libraries/ok-jacks
LibName44=D:/JottaCloud/Jottacloud/Prosjekt/KiCad bibliotek/libraries/ok-opto
LibName45=D:/JottaCloud/Jottacloud/Prosjekt/KiCad bibliotek/libraries/ok-power
LibName46=D:/JottaCloud/Jottacloud/Prosjekt/KiCad bibliotek/libraries/ok-relay
LibName47=D:/JottaCloud/Jottacloud/Prosjekt/KiCad bibliotek/libraries/ok-switches
LibName48=D:/JottaCloud/Jottacloud/Prosjekt/KiCad bibliotek/libraries/ok-transformers
LibName49=D:/JottaCloud/Jottacloud/Prosjekt/KiCad bibliotek/libraries/ok-transistors
LibName50=D:/JottaCloud/Jottacloud/Prosjekt/KiCad bibliotek/ElecroQuark/Libraries/IFS-Capacitors
LibName51=D:/JottaCloud/Jottacloud/Prosjekt/KiCad bibliotek/ElecroQuark/Libraries/IFS-Connectors
LibName52=D:/JottaCloud/Jottacloud/Prosjekt/KiCad bibliotek/ElecroQuark/Libraries/IFS-Diodes
LibName53=D:/JottaCloud/Jottacloud/Prosjekt/KiCad bibliotek/ElecroQuark/Libraries/IFS-Displays
LibName54=D:/JottaCloud/Jottacloud/Prosjekt/KiCad bibliotek/ElecroQuark/Libraries/IFS-Microcontrollers
LibName55=D:/JottaCloud/Jottacloud/Prosjekt/KiCad bibliotek/ElecroQuark/Libraries/IFS-Motor.Drivers
LibName56=D:/JottaCloud/Jottacloud/Prosjekt/KiCad bibliotek/ElecroQuark/Libraries/IFS-Power
LibName57=D:/JottaCloud/Jottacloud/Prosjekt/KiCad bibliotek/ElecroQuark/Libraries/IFS-Resistors
LibName58=D:/JottaCloud/Jottacloud/Prosjekt/KiCad bibliotek/ElecroQuark/Libraries/IFS-Sensors
LibName59=D:/JottaCloud/Jottacloud/Prosjekt/KiCad bibliotek/ElecroQuark/Libraries/IFS-Special
LibName60=D:/JottaCloud/Jottacloud/Prosjekt/KiCad bibliotek/ElecroQuark/Libraries/IFS-Switches
LibName61=D:/JottaCloud/Jottacloud/Prosjekt/KiCad bibliotek/ElecroQuark/Libraries/IFS-Transformers
LibName62=D:/JottaCloud/Jottacloud/Prosjekt/KiCad bibliotek/ElecroQuark/Libraries/IFS-Transistors
LibName63=D:/JottaCloud/Jottacloud/Prosjekt/KiCad bibliotek/ElecroQuark/Libraries/IFS-Voltage.Regulators
LibName64=D:/JottaCloud/Jottacloud/Prosjekt/KiCad bibliotek/ElecroQuark/Libraries/IFS-XTALs
